### ISSUE TITLE
Follow the original entries object on rebuilds

### ISSUE THREAD

**Issue by Luk-z** [momentumdash/vite-plugin-incremental-build#1]
On rebuilds the original entries object should be used.

**Real world case:**
We are working on a `Vite` library using `next.js` and `React 18` (as peer deps).
We are using `rollupOptions.input` option to strip "lib" folder (eg. `lib/components/Foo.tsx` -> will be compiled in `dist/components/Foo.js`).
The first time we start incremental build all works fine. When we edit `Foo.tsx` the new compiled file will be placed in `dist/lib/components/Foo.js`.

ref: https://github.com/vitejs/vite/issues/16104#issuecomment-2222944293

**Comment by Samydookie** [comment]
Fixed in 1.0.5

**Comment by Luk-z** [comment]
@Samydookie the `watcherModifiedFile` now it's compiled in the correct folder, but files imported by `watcherModifiedFile` are compiled in the wrong folder. I dont't think this will break the project because these files are not referenced but creates some dirty files in the dist folder

eg.
```
// lib/components/Foo.tsx
import Bar from "./Bar"
...
...
```
`lib/components/Foo.tsx` is compiled correctly in `dist/components/Foo.js` as specified in `rollupOptions.input`.
`lib/components/Bar.tsx` is compiled in `dist/lib/components/Bar.js`

**Comment by Luk-z** [comment]
also i would use path.resolve to handle relative root dir

```
const findMatching = (item) => {
    return  path.resolve(item[1]) ===  path.resolve(config.root + '/' + watcherModifiedFile);
}
```

I can open a PR if you want

**Comment by Samydookie** [comment]
> @Samydookie the `watcherModifiedFile` now it's compiled in the correct folder, but files imported by `watcherModifiedFile` are compiled in the wrong folder. I dont't think this will break the project because these files are not referenced but creates some dirty files in the dist folder
> 
> eg.
> 
> ```
> // lib/components/Foo.tsx
> import Bar from "./Bar"
> ...
> ...
> ```
> 
> `lib/components/Foo.tsx` is compiled correctly in `dist/components/Foo.js` as specified in `rollupOptions.input`. `lib/components/Bar.tsx` is compiled in `dist/lib/components/Bar.js`

@Luk-z Yeah I'm not sure there is a clean way to handle an input importing another input. As far as I can tell inputs should mainly be used for things like service workers (and including html files). 
It sounds like you might get better results if you set your root folder as './lib', or if you set your input options to do your `/lib` path rewrite only when you're running a production build, and incremental builds can follow your original project structure.
Unless I'm missing something about your use case that would make it not work

**Comment by Luk-z** [comment]
We use input to have clean folder structure for [package exports](https://webpack.js.org/guides/package-exports) (we don't want user imports a component from `mylib/lib/components/Foo`, instead we want `mylib/components/Foo`).
If you know better solution to achieve this behavior you are welcome!

I expect when vite/rollup compile `Bar.tsx` takes care of what specified in `rollupOptions.input`.

**Comment by Samydookie** [comment]
> We use input to have clean folder structure for [package exports](https://webpack.js.org/guides/package-exports) (we don't want user imports a component from `mylib/lib/components/Foo`, instead we want `mylib/components/Foo`). If you know better solution to achieve this behavior you are welcome!
> 
> I expect when vite/rollup compile `Bar.tsx` takes care of what specified in `rollupOptions.input`.

Ah I see, in your case I would probably suggest:
- not using `rollupOptions.input` when you are running builds with the incremental plugin (in development)
- keep `rollupOptions.input` for real (production) builds meant to be published
- (optional) in your project that tests your library (from the source), I would add an alias to map `mylib/component` to `mylib/lib/components`

If not using the alias, you can import using `mylib/lib/components` but I can totally see how you would want your testing code to serve as examples.
That way you can add however many components you want and assuming your `rollupOptions.input` are built dynamically you don't have to change anything with the build

**Comment by Luk-z** [comment]
Ok your solution is clear. 
On the other hand probably this will be not a problem because when I edit `Foo.tsx` the current and fresh version of `Bar.tsx` will be always in the right folder.
I will have a dirty folder with some compiled files but a fresh version of this files will be in the right folder.
When I edit `Bar.tsx` the correct file is compiled in the right folder according with the `rollupOptions.input` option.
